### ISSUE TITLE
BUG it says checking for updates on mobile and ive uninstalled and it still says that

### ISSUE THREAD

**Issue by Eliastoocxry** [Alex-mar124/EZFN-Bugs#12]
**Describe the bug**
A clear and concise description of what the bug is HERE:.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 on mobile and ive uninstalled and it still says that

**Comment by Alex-mar124** [comment]
Please add more detail to your issue,
Thanks Alex
Head Management / Community Operations
