### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by frgdxgtey** [Alex-mar124/EZFN-Bugs#2]
Pc:

I'm using the un-updated ezfn launcher because when I use the other one it crashes, After I got it working I try to join Solo Match It goes back to lobby then it freezes

**Comment by Alex-mar124** [comment]
Hey, EZFN for some people may be broken at the moment ask in the discord on how to fix it, EZFN Also does not support going in game yet, please wait for the update coming soon that will add it. Thanks!
