### ISSUE TITLE
BUG:when i launch the hybrid the application dosent respond 

### ISSUE THREAD

**Issue by xyzary** [Alex-mar124/EZFN-Bugs#4]
**Describe the bug**
A clear and concise description of what the bug is HERE:.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Zolifaa** [comment]
thats pretty normal it wont respond then press it and it will still do not respond and then it will work

**Comment by Alex-mar124** [comment]
Hey,
as said above it may take a few tries as it has to start a local server if you are having anymore issues please join the discord :) 
Thanks Alex
Head Management / Community Operations
